require_relative './lib/file_sorter_tool/version'

task default: 'app:update'

namespace :app do

  desc 'Uninstall gem'
  task :uninstall do
    `gem uninstall -x file_sorter_tool`
    `rm file_sorter_tool-*.gem`
    puts "uninstall...[OK]"
  end

  desc 'Build gem'
  task :build do
    `gem build file_sorter_tool.gemspec`
    puts "build...[OK]"
  end

  desc 'Install gem'
  task :install do
    `gem install file_sorter_tool-*.gem`
    puts "install...[OK]"
  end

  desc <<-DESC
    inc gem version
  DESC
  task :next_version do
    path = File.expand_path '../lib/file_sorter_tool/version.rb', __FILE__

    file = File.open path
    file_content = file.read
    file.close

    next_version = FileSorterTool.version.next.split '.'

    file_content.gsub! /MAJOR = '.'/, "MAJOR = '#{next_version[0]}'"
    file_content.gsub! /MINOR = '.'/, "MINOR = '#{next_version[1]}'"
    file_content.gsub! /PATCH = '.'/, "PATCH = '#{next_version[2]}'"

    File.open(path, 'w') { |file| file.write file_content}
    puts "Next version generate...[OK]"
  end

  desc 'Update gem (reinstall)'
  task update: [:uninstall, :next_version, :build, :install] do
      puts "Reinstall...[OK]"
  end
end
