require_relative 'lib/download_sorter.rb'

task default: 'ds:help'

namespace :ds do

  desc 'help'
  task :help do
    puts 'Files in current directory sorter. Make directory for each file extenfion and move files into this directories'
  end

  desc 'do sorting'
  task :sort,  [:path] do |t, args|
    path = args[:path] != nil ? args[:path] : "/Volumes/DATA/Downloads"
    Dir.chdir(path)
    Dir['*'].each.with_index do |file, index|
      DownloadSorter::process_file file
    end
    puts "Files sorting success..."
  end
end
